---
- name: restart rapidpro-indexer
  systemd:
    name: "{{ rapidpro_indexer_service_name }}"
    state: restarted
    enabled: true
    daemon_reload: true
  when: not rapidpro_indexer_install_only | default(false)
