---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ansible-rapidpro-indexer-ubuntu-18.04
    image: solita/ubuntu-systemd:18.04
    dockerfile: Dockerfile.j2
    privileged: true
    command: /sbin/init
provisioner:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8
verifier:
  name: testinfra
